### ISSUE TITLE
[PE-D] parameter correct but invalid

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-3/tp#253]
![image.png](https://raw.githubusercontent.com/JaCh23/ped/main/files/8df297a8-6669-435c-8e18-efb3ff973628.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: JaCh23/ped#1

**Comment by rizemon** [comment]
Perhaps include in table listing of modules mentioned in #260.
