### ISSUE TITLE
[PE-D] Unable to Exit from Editing Mode for Recipe

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-3/tp#255]
After creating a new recipe/editing a recipe, [Editing: <recipeName>] remains in the terminal input name even while carrying out other operations.

![image.png](https://raw.githubusercontent.com/renzocanare/ped/main/files/77e673ce-8c43-4797-8328-a27f85deddad.png)

This may present itself as confusing to the user, and you can consider having an option to "exit" editing mode.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: renzocanare/ped#2

**Comment by rizemon** [comment]
Same as #262
