### ISSUE TITLE
[PE-D] Missing Argument Description for "Selecting a Module or Recipe" in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-3/tp#260]
In the UG, you can consider noting which modules will accept the {moduleArgument}. As your user guide is tailored for CTF players with a basic understanding of security concepts, this may not necessarily mean that your users will be certain how your program works as well. It will be of great help to new CTF players too if you could specify when the additional arguments are not required.

![image.png](https://raw.githubusercontent.com/renzocanare/ped/main/files/2eb042e5-7407-4b23-93eb-5b41e40c9fe1.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: renzocanare/ped#3

**Comment by arraysius** [comment]
Can perhaps have a table listing the modules with and without parameters.
