### ISSUE TITLE
[PE-D] recipe new with no <recipeName> throws Incorrect Exception

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-3/tp#261]
When `recipe new ` (note the space after new) is input by the user, the exception "Too many command arguments" is returned. In this case, you may consider changing the exception thrown to "recipeName has not been entered" since there is actually one less argument not input.

![image.png](https://raw.githubusercontent.com/renzocanare/ped/main/files/5c0edec2-4c95-4137-a743-675a5562d22c.png)

Edit: This applies to all recipe <command> functions as well, when an argument where expected is not input.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: renzocanare/ped#4

**Comment by rizemon** [comment]
At https://github.com/AY2122S1-CS2113T-T10-3/tp/blob/master/src/main/java/decodex/parser/RecipeCommandParser.java#L89

Perhaps instead of checking whether the number of arguments is not equal to the correct number of arguments, we divide this into 2 cases: less than and more than.
