### ISSUE TITLE
[PE-D] No way to deselect a recipe

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-3/tp#262]
Before any recipes are added, other small inputs can be conducted when there are no recipes selected for editing, where the CLI will show `Decodex []`. However, once any recipes are added, the program will automatically have a recipe selected for editing. Hence `list recipes` can be called while editing a recipe which could mislead the user to think that recipes can be nested.'

![ped4.png](https://raw.githubusercontent.com/alwinangys/ped/main/files/c4edc1ba-c524-43c6-9fb2-c72afc81b648.png)

Perhaps there could be a way to deselect recipes and return to the original state without having to invoke the `delete` command, as it seems to be the only way to deselect from all recipes now.

![ped5.png](https://raw.githubusercontent.com/alwinangys/ped/main/files/086de543-0817-488d-a724-37d98d4aa714.png)

Just a small issue, but could potentially confuse users.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: alwinangys/ped#3

**Comment by rizemon** [comment]
Perhaps add a `recipe unselect` that will unselect the currently edited recipe.
