### ISSUE TITLE
[PE-D] Outdated documentation in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-3/tp#265]
![image.png](https://raw.githubusercontent.com/jyxhazcake/ped/main/files/15917c4f-2969-4866-b51b-bb80242ce972.png)

Commands in this image are outdated.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: jyxhazcake/ped#3

**Comment by arraysius** [comment]
Duplicate of #268
