### ISSUE TITLE
[PE-D] exit command can have trailing letters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-3/tp#267]
![image.png](https://raw.githubusercontent.com/JaCh23/ped/main/files/b6cb9033-eb0e-4ffe-aa85-d19e539f59f3.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: JaCh23/ped#4

**Comment by rizemon** [comment]
Code should check that there are `0` arguments and if there are, should reflect an error saying that there are too many arguments.
