### ISSUE TITLE
[PE-D] No way to decode or encode without a recipe while UG suggests so

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-3/tp#268]
The UG shows that this is an example of decoding:

![ped7.png](https://raw.githubusercontent.com/alwinangys/ped/main/files/8f347911-99b3-4f17-a933-0a6fcb46b812.png)

However, it seems like without a recipe, this can no longer be done. The user would be unable to quickly test encoding and decoding of a string without a recipe added.

![ped8.png](https://raw.githubusercontent.com/alwinangys/ped/main/files/8c1d9b3b-9cf7-4f90-8244-9f9c537205a3.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: alwinangys/ped#5

**Comment by rizemon** [comment]
Outdated picture, just need to update it to follow the new command syntaxes.
