### ISSUE TITLE
[PE-D] Recipe Command Header is same size as those below it, but is different level in Table of Contents

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-3/tp#270]
The "Recipe Commands" header may confuse readers, since it is the same size as the commands below it but is on a different level in the table of commands.

![image.png](https://raw.githubusercontent.com/renzocanare/ped/main/files/bff03687-690f-4fe3-ad01-6c1615041212.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: renzocanare/ped#6

**Comment by rizemon** [comment]
Rejectedd as reviewer was viewing an outdated version of the user guide.
