### ISSUE TITLE
Ui methods missing parameters

### ISSUE THREAD

**Issue by rizemon** [AY2122S1-CS2113T-T10-3/tp#333]
![image](https://user-images.githubusercontent.com/26685970/140656841-29a77519-68cb-4d40-823a-345c8b456b9d.png)

The 3 methods in Ui are missing their parameters. Refer to their code here: https://github.com/AY2122S1-CS2113T-T10-3/tp/blob/master/src/main/java/decodex/ui/Ui.java

**Comment by Kair0s3** [comment]
Only printSuccess and printError are missing parameters
